### ISSUE TITLE
Configuration File

### ISSUE THREAD

**Issue by azz** [linterjs/core#1]
_No `cli` repository yet, so opening it here_

Obviously a configuration file is required. I had a few ideas rattling in my head so I thought I'd jot down some examples.

**Equivalent of `eslint-config-prettier` and `tslint-config-prettier`:**

```json
// .linterrc
{
  "rules": [
    {
      "files": "*.tsx?",
      "use": ["tslint", "prettier"]
    },
    {
      "files": ["*.jsx?", "*.md"],
      "use": ["eslint", "prettier"]
    }
  ]
}
```

**Equivalent of `prettier-eslint` and `prettier-tslint`:**

```json
{
  "rules": [
    {
      "files": "*.tsx?",
      "use": ["prettier", "eslint"]
    },
    {
      "files": ["*.jsx?", "*.md"],
      "use": ["prettier", "eslint"]
    }
  ]
}
```

**Passing options to a linter:**

```json
{
  "rules": [
    {
      "files": "*.js",
      "use": [
        ["prettier", { "tabWidth": 4 }],
        ["eslint", { "extends": ["standard", "prettier"] }]
      ]
    }
  ]
}
```

Note that the resolution for names in `"use"` would be:

1. `resolve("@linter/" + name)`
1. `resolve("linter-" + name)`
1. `resolve(name)`

**Comment by zimme** [comment]
I'm hoping we can do without a config file tbh.

For the linting part of this the order in which the linters run is not important.
For formatting the code I'm thinking we should always run prettier first, if it's registered.

So you would basically configure @linter by installing the adapters that you're interested in and the adapters would run on all files they support and/or are configured to run on, via their respective config files.

**Comment by zimme** [comment]
Let's keep the discussion going in linterjs/cli#1.
