### ISSUE TITLE
Discord Server

### ISSUE THREAD

**Issue by Shinigami92** [linterjs/core#20]
# Initiate Discord Server

## Summary

Create a Discord Community Server

## Motivation

On a Discord Commuinty Server we can quickly answer questions and provide support for simple problems.  
Also we can create private channels to discuss internal ideas/proposals.  
In addition we can add channels linked with WebHooks so we can listen to any changes within the repos.

## Detailed Design

Channels with different purposes can be created on demand.

## Documentation

Add Badge to the `README.md`.

## Drawbacks

It's free, I don't think there are any drawbacks.

## Alternatives

Other Chat Application like Gitter or Slack?  
But I'm really often using Discord. (~ 5-10h per day)

## Open Questions

Who should maintain the server? We should allow Core Team members to maintain the server.

## Help Needed

Don't think so.

## Frequently Asked Questions

Currently none

## Related Discussions

Currently none

**Comment by Shinigami92** [comment]
@zimme @azz 
Would you be happy when I create and manage this Discord server. Of course I will grant you admin permissions if you want to also join this server.
Or do we want something different?

**Comment by zimme** [comment]
I'm ok with any community solution as long as it doesn't require some kind of invite like Slack as that's just not inclusive enough in my mind. I've created a Spectrum community and I'll grant anyone of you admin access if you want.

Also, I see no reason for multiple community solutions to co-exist, different people prefer different formats.

**Comment by Shinigami92** [comment]
So I created https://discord.gg/cNUqYNq
Will create a PR for README.md later

**Comment by Shinigami92** [comment]
Created the Webhook
this comment is also a test :)
