### ISSUE TITLE
Setup testing

### ISSUE THREAD

**Issue by zimme** [linterjs/core#4]
I'm leaning towards [`tape`](https://github.com/substack/tape) for testing, at least as long as we only have unit tests. It works with typescript and it's simple.

**Comment by azz** [comment]
Jest snapshot testing has been invaluable for Prettier. I pretty much pick Jest for anything nowadays.

**Comment by zimme** [comment]
I don't have a problem using jest either. Do we need snapshot testing? Let's start with unit testing first and see where we might need more advanced testing?

**Comment by zimme** [comment]
I've setup jest for testing now.
